name: mdsite
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cosmic_frontmatter: ^1.0.3
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get: 4.6.6
  intl: null
  json_annotation: ^4.8.1
  markdown_widget: ^2.3.2+6
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/data.json
